apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    solvers:

    # example: cross-account zone management for example.com
    # this solver uses ambient credentials (i.e. inferred from the environment or EC2 Metadata Service)
    # to assume a role in a different account
    - selector:
        dnsZones:
          - "cloud.cttexpress.com"  
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: surj@polarpoint.io
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
      - name: route53
        route53:
          region: eu-west-1
          accessKeyID: AKIA35DMEUA6DRLZ66XH
          secretAccessKeySecretRef:
            name: acme-route53
            key: secret-access-key
