## External DNS
image:
  name: registry.opensource.zalan.do/teapot/external-dns
  tag: v0.5.14

## This controls which types of resource external-dns should 'watch' for new
## DNS entries.
sources:
  - service
  - ingress

## The DNS provider where the DNS records will be created (options: aws, google, inmemory, azure, rfc2136 )
provider: aws

# AWS Access keys to inject as environment variables
aws:
  roleArn: "arn:aws:iam::818418065468:role/AllowExternalDNS_Role"
  region: "eu-west-1"
  # Filter for zones of this type (optional, options: public, private)
  zoneType: "private"

## Limit possible target zones by domain suffixes (optional)
domainFilters: [cloud.cttexpress.com]
## Limit possible target zones by zone id (optional)
zoneIdFilters: []
# Filter sources managed by external-dns via annotation using label selector semantics (default: all sources)
annotationFilter: ""
## Adjust the interval for DNS updates
interval: "1m"

# Registry to use for ownership (txt or noop)
registry: "txt"

# When using the TXT registry, a name that identifies this instance of ExternalDNS
txtOwnerId: "Z01519431KDNST8VL5KJC"

## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only )
policy: upsert-only

# Verbosity of the logs (options: panic, debug, info, warn, error, fatal)
logLevel: info

## CPU and Memory limit and request for external-dns
resources:
  limits:
    memory: 50Mi
  requests:
    memory: 50Mi
    cpu: 10m

rbac:
  create: true
  serviceAccountName: external-dns


   helm install external-dns stable/external-dns \                             
--set provider=aws \
--set policy=sync \
--set registry=txt \
--set txtOwnerId=Z01519431KDNST8VL5KJC \
--set interval=3m \
--set rbac.create=true \
--set rbac.serviceAccountName=external-dns \
--set rbac.serviceAccountAnnotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::818418065468:role/AllowExternalDNS_Role \
--set aws.roleArn="arn:aws:iam::818418065468:role/AllowExternalDNS_Role" \
--set aws.region="eu-west-1" \
--set aws.zoneType="private"