---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: github-personal-access-token 
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::818418065468:role/eksctl-shared-services-eks-iamserviceaccount-role
  data:
    - key: service/github/token
      name: password
    - key: service/github/user
      name: username
