---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: github-personal-access-token
  namespace: continuous-integration
spec:
  backendType: secretsManager
  data:
    - key: service/github/personalAccessToken
      name: password
    - key: service/github/username
      name: username 