---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: github-service-account 
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::818418065468:role/eksctl-shared-services-eks-iamserviceaccount-role
  dataFrom:
    - github-service-account/credentials
