---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: default
spec:
  releaseName: external-secrets
  chart:
    repository: https://godaddy.github.io/kubernetes-external-secrets/
    name: kubernetes-external-secrets
    version: 5.2.0
  values:
    env:
      AWS_REGION: eu-west-1
      AWS_DEFAULT_REGION: eu-west-1
