---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: default
spec:
  releaseName: external-secrets
  chart:
    repository: https://godaddy.github.io/kubernetes-external-secrets/
    name: kubernetes-external-secrets
    version: 5.2.0
  values:
    env:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_REGION: eu-west-1
    securityContext:
      fsGroup: 65534
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::818418065468:role/eksctl-shared-services-eks-service-account-role