---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: default
spec:
  releaseName: external-secrets
  chart:
    repository: https://godaddy.github.io/kubernetes-external-secrets/
    name: kubernetes-external-secrets
    version: 5.2.0
  values:
    # Default values for kubernetes-external-secrets.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    # Determines whether the Helm chart or kubernetes-external-secrets
    # will handle the ExternalSecret CRD
    customResourceManagerDisabled: false

    crds:
      # only needed for helm v2, leave this disabled for helm v3
      create: false

    env:
      AWS_REGION: eu-west-1
      AWS_DEFAULT_REGION: eu-west-1
    # Environment variables to set on deployment pod
    env:
      AWS_REGION: us-west-1
      AWS_DEFAULT_REGION: us-west-1
      POLLER_INTERVAL_MILLISECONDS: 10000  # Caution, setting this frequency may incur additional charges on some platforms
      LOG_LEVEL: info
      LOG_MESSAGE_KEY: 'msg'
      # Print logs level as string ("info") rather than integer (30)
      # USE_HUMAN_READABLE_LOG_LEVELS: true
      METRICS_PORT: 3001
      VAULT_ADDR: http://127.0.0.1:8200


    rbac:
      # Specifies whether RBAC resources should be created
      create: true

    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # Specifies annotations for this service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: 

    replicaCount: 1

    image:
      repository: godaddy/kubernetes-external-secrets
      tag: 5.2.0
      pullPolicy: IfNotPresent
      imagePullSecrets: []

    nameOverride: ""
    fullnameOverride: ""
    podAnnotations: "eks.amazonaws.com/role-arn=arn:aws:iam::818418065468:policy/kube-external-secrets"
    podLabels: {}

    dnsConfig: {}

    securityContext:
      runAsNonRoot: true
      # Required for use of IRSA, see https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
      fsGroup: 65534

    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    nodeSelector: {}

    tolerations: []

    affinity: {}

    serviceMonitor:
      enabled: false
      interval: "30s"
      namespace: